package com.code.enums;

/**
 * This enumeration contains all the menu actions that will be used at the application for granting special privileges for users
 * <p>
 * Naming convention as follows:<br>
 * Constant: Module abbreviation + "_" + Screen name + "_" + action name<br>
 * Value: "ETR_HCM_" + Module abbreviation + "_" + Screen name + "_" + action name (Except ETR actions ETR_ not ETR_HCM_).
 */
public enum MenuActionsEnum {

    ETR_DECISION_TEMPLATES_ADMIN("ETR_DECISION_TEMPLATES_ADMIN"),
    ETR_SIGNATURES_MANAGEMENT_ADMIN("ETR_SIGNATURES_MANAGEMENT_ADMIN"),
    ETR_SYSTEM_CONFIGURATIONS_ADMIN("ETR_SYSTEM_CONFIGURATIONS_ADMIN"),

    WF_INBOX_OUTBOX_ADMIN_OFFICERS("ETR_HCM_WF_INBOX_OUTBOX_ADMIN_OFFICERS"),
    WF_INBOX_OUTBOX_ADMIN_SOLDIERS("ETR_HCM_WF_INBOX_OUTBOX_ADMIN_SOLDIERS"),
    WF_INBOX_OUTBOX_ADMIN_CIVILIANS("ETR_HCM_WF_INBOX_OUTBOX_ADMIN_CIVILIANS"),
    WF_SEND_NOTIFICATION_MESSAGES("ETR_HCM_WF_SEND_NOTIFICATION_MESSAGES"),

    VAC_CONFIGURATIONS_MODIFY("ETR_HCM_VAC_CONFIGURATIONS_MODIFY"),

    VAC_BALANCE_INQUIRY_SHOW_ALL_OFFICERS("ETR_HCM_VAC_BALANCE_INQUIRY_SHOW_ALL_OFFICERS"),
    VAC_BALANCE_INQUIRY_SHOW_ALL_SOLDIERS("ETR_HCM_VAC_BALANCE_INQUIRY_SHOW_ALL_SOLDIERS"),
    VAC_BALANCE_INQUIRY_SHOW_ALL_CIVILIANS("ETR_HCM_VAC_BALANCE_INQUIRY_SHOW_ALL_CIVILIANS"),

    VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_OFFICERS("ETR_HCM_VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_OFFICERS"),
    VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_SOLDIERS("ETR_HCM_VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_SOLDIERS"),
    VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_EMPLOYEES("ETR_HCM_VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_EMPLOYEES"),

    VAC_VACATION_REQUEST_ALL_OFFICERS("ETR_HCM_VAC_VACATION_REQUEST_ALL_OFFICERS"),
    VAC_VACATION_REQUEST_ALL_SOLDIERS("ETR_HCM_VAC_VACATION_REQUEST_ALL_SOLDIERS"),
    VAC_VACATION_REQUEST_ALL_EMPLOYEES("ETR_HCM_VAC_VACATION_REQUEST_ALL_EMPLOYEES"),

    VAC_VACATIONS_REPORTS_FOR_ALL("ETR_HCM_VAC_VACATIONS_REPORTS_FOR_ALL"),

    JOBS_REPORTS_SHOW_JOBS_IN_TRANSACTIONS_REPORTS("ETR_HCM_JOBS_REPORTS_SHOW_JOBS_IN_TRANSACTIONS_REPORTS"),
    JOBS_BALANCES_MODIFY("ETR_HCM_JOBS_BALANCES_MODIFY"),
    JOBS_RANKS_POWER_MANAGMENT_MODIFY("ETR_HCM_RANKS_POWER_MANAGMENT_MODIFY"),

    PRS_EMPS_DATA_VIEW_MODIFY_OFFICERS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_OFFICERS"),
    PRS_EMPS_DATA_VIEW_MODIFY_SOLDIERS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_SOLDIERS"),
    PRS_EMPS_DATA_VIEW_MODIFY_CIVILIANS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_CIVILIANS"),
    PRS_EMPS_DATA_VIEW_SHOW_OFFICERS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_OFFICERS"),
    PRS_EMPS_DATA_VIEW_SHOW_SOLDIERS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_SOLDIERS"),
    PRS_EMPS_DATA_VIEW_SHOW_CIVILIANS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_CIVILIANS"),
    PRS_EMPS_DATA_VIEW_SHOW_COMMUNICATIONS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_COMMUNICATIONS"),
    PRS_EMPS_DATA_VIEW_MODIFY_COMMUNICATIONS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_COMMUNICATIONS"),

    PRS_EMPS_DATA_REPORTS_VIEW_ALL_OFFICERS("ETR_HCM_PRS_EMPS_DATA_REPORTS_VIEW_ALL_OFFICERS"),
    PRS_EMPS_DATA_REPORTS_VIEW_ALL_SOLDIERS("ETR_HCM_PRS_EMPS_DATA_REPORTS_VIEW_ALL_SOLDIERS"),
    PRS_EMPS_DATA_REPORTS_VIEW_ALL_CIVILIANS("ETR_HCM_PRS_EMPS_DATA_REPORTS_VIEW_ALL_CIVILIANS"),

    PRS_EMPS_FILE_MODIFY_OFFICERS("ETR_HCM_PRS_EMPS_FILE_MODIFY_OFFICERS"),
    PRS_EMPS_FILE_MODIFY_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_MODIFY_SOLDIERS"),
    PRS_EMPS_FILE_MODIFY_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_MODIFY_CIVILIANS"),
    PRS_EMPS_FILE_VIEW_OFFICERS("ETR_HCM_PRS_EMPS_FILE_VIEW_OFFICERS"),
    PRS_EMPS_FILE_VIEW_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_VIEW_SOLDIERS"),
    PRS_EMPS_FILE_VIEW_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_VIEW_CIVILIANS"),

    PRS_EMPS_FILE_REPORT_SHOW_OFFICERS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_OFFICERS"),
    PRS_EMPS_FILE_REPORT_SHOW_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_SOLDIERS"),
    PRS_EMPS_FILE_REPORT_SHOW_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_CIVILIANS"),

    PRS_ADDITIONAL_SPECS_MVT_BLACKLIST("ETR_HCM_PRS_ADDITIONAL_SPECS_MVT_BLACKLIST"),
    PRS_ADDITIONAL_SPECS_MVT_UNBLACKLIST("ETR_HCM_PRS_ADDITIONAL_SPECS_MVT_UNBLACKLIST"),

    REC_EMPS_REGISTRATION_SHOW_OFFICERS("ETR_HCM_REC_EMPS_REGISTRATION_SHOW_OFFICERS"),
    REC_EMPS_REGISTRATION_SHOW_SOLDIERS("ETR_HCM_REC_EMPS_REGISTRATION_SHOW_SOLDIERS"),
    REC_EMPS_REGISTRATION_SHOW_CIVILIANS("ETR_HCM_REC_EMPS_REGISTRATION_SHOW_CIVILIANS"),
    REC_EMPS_REGISTRATION_INSERT_OFFICERS("ETR_HCM_REC_EMPS_REGISTRATION_INSERT_OFFICERS"),
    REC_EMPS_REGISTRATION_INSERT_SOLDIERS("ETR_HCM_REC_EMPS_REGISTRATION_INSERT_SOLDIERS"),
    REC_EMPS_REGISTRATION_INSERT_CIVILIANS("ETR_HCM_REC_EMPS_REGISTRATION_INSERT_CIVILIANS"),
    REC_EMPS_REGISTRATION_MODIFY_OFFICERS("ETR_HCM_REC_EMPS_REGISTRATION_MODIFY_OFFICERS"),
    REC_EMPS_REGISTRATION_MODIFY_SOLDIERS("ETR_HCM_REC_EMPS_REGISTRATION_MODIFY_SOLDIERS"),
    REC_EMPS_REGISTRATION_MODIFY_CIVILIANS("ETR_HCM_REC_EMPS_REGISTRATION_MODIFY_CIVILIANS"),
    REC_RECRUITMENT_WISHES_MODIFY("ETR_HCM_REC_RECRUITMENT_WISHES_MODIFY"),

    // MVT Menu Actions
    MVT_INTERNAL_ASSIGNMENT_MANAGER_OFFICERS("ETR_HCM_MVT_INTERNAL_ASSIGNMENT_MANAGER_OFFICERS"),
    MVT_INTERNAL_ASSIGNMENT_MANAGER_SOLDIERS("ETR_HCM_MVT_INTERNAL_ASSIGNMENT_MANAGER_SOLDIERS"),
    MVT_INTERNAL_ASSIGNMENT_MANAGER_CIVILIANS("ETR_HCM_MVT_INTERNAL_ASSIGNMENT_MANAGER_CIVILIANS"),
    MVT_MOVE_WISHES_ADMIN("ETR_HCM_MVT_MOVE_WISHES_ADMIN"),
    // MSN Menu Actions
    MSN_BALANCE_INQUIRY_SHOW_ALL_OFFICERS("ETR_HCM_MSN_BALANCE_INQUIRY_SHOW_ALL_OFFICERS"),
    MSN_BALANCE_INQUIRY_SHOW_ALL_SOLDIERS("ETR_HCM_MSN_BALANCE_INQUIRY_SHOW_ALL_SOLDIERS"),
    MSN_BALANCE_INQUIRY_SHOW_ALL_PERSONS("ETR_HCM_MSN_BALANCE_INQUIRY_SHOW_ALL_PERSONS"),
    MSN_REQUEST_SEND_ALL_OFFICERS("ETR_HCM_MSN_REQUEST_SEND_ALL_OFFICERS"),
    MSN_REQUEST_SEND_ALL_SOLDIERS("ETR_HCM_MSN_REQUEST_SEND_ALL_SOLDIERS"),
    MSN_REQUEST_SEND_ALL_PERSONS("ETR_HCM_MSN_REQUEST_SEND_ALL_PERSONS"),
    MSN_INQUIRY_REPORT("ETR_HCM_MISSION_STATISTICAL_REPORT_INQUIRY"),

    // PRM Menu Actions
    PRM_OFFICER_REPORT_BRIGADIER_PROMOTE("ETR_HCM_PRM_OFFICER_REPORT_BRIGADIER_PROMOTE"),
    PRM_DECISION_SOLDIERS_CANCELLATION("ETR_HCM_PRM_DECISION_SOLDIERS_CANCELLATION"),

    // DEF LETTER Menu Actions
    DEF_LETTERS_SHOW_ALL_OFFICERS("ETR_HCM_DEFINITION_LETTERS_SHOW_ALL_OFFICERS"),
    DEF_LETTERS_SHOW_ALL_SOLDIERS("ETR_HCM_DEFINITION_LETTERS_SHOW_ALL_SOLDIERS"),
    DEF_LETTERS_SHOW_ALL_EMPLOYEES("ETR_HCM_DEFINITION_LETTERS_SHOW_ALL_EMPLOYEES"),

    // Training - Menu actions
    TRN_MILITARY_COURSES_INSERT_MODIFY("ETR_HCM_TRN_MILITARY_COURSES_INSERT_MODIFY"),
    TRN_EMPLOYEE_TRAINING_FILE_MODIFY("ETR_HCM_TRN_EMPLOYEE_TRAINING_FILE_MODIFY"),
    TRN_EMPLOYEE_TRAINING_FILE_DELETE_CLAIM("TRN_EMPLOYEE_TRAINING_FILE_DELETE_CLAIM"),
    TRN_CLAIMS_REQUEST("ETR_HCM_TRN_CLAIMS_REQUEST"),
    TRN_MILITARY_REQUEST_REGION_ADMIN("ETR_HCM_TRN_MILITARY_REQUEST_REGION_ADMIN"),
    TRN_UNIT_SPECIALIST("ETR_HCM_TRN_UNIT_SPECIALIST"),
    TRN_EMPLOYEES_TRAINING_TRANSACTIONS_INQUIRY_ADMIN("ETR_HCM_TRN_EMPLOYEES_TRAINING_TRANSACTIONS_INQUIRY_ADMIN"),
    TRN_MILITARY_COURSES_INSERT_MODIFY_ATTACHMENTS("ETR_HCM_TRN_MILITARY_COURSES_INSERT_MODIFY_ATTACHMENTS"),
    TRN_TRAINING_PLAN_DETAILS_EXCEL_PRINT("ETR_HCM_TRN_TRAINING_PLAN_DETAILS_EXCEL_PRINT"),
    // Martyrs - Menu Actions
    MARTYRS_TRANSACTIONS_DATA_MODIFY_DELETE("ETR_HCM_MARTYRS_DATA_MODIFY_DELETE"),

    RET_DISCLAIMER_REQUEST_CREATE("ETR_HCM_RET_DISCLAIMER_REQUEST_CREATE"),

    // Raises Menu Actions
    RAISES_APPROVE_ANNUAL_RAISE_REGISTRATION("ETR_HCM_RAISES_APPROVE_ANNUAL_RAISE"),
    RAISES_APPROVE_ADDITIONAL_RAISE("ETR_HCM_RAISES_APPROVE_ADDITIONAL_RAISE");

    private String code;

    private MenuActionsEnum(String code) {
	this.code = code;
    }

    public String getCode() {
	return code;
    }
}
