package com.code.enums;

public enum WFPositionsEnum {
    // Presidency.
    VICE_PRESIDENT(2),
    MILITARY_AFFAIRS_ASSISTANT(840),

    // Officers Affairs.
    OFFICERS_ARCHIVES_UNIT_MANAGER(10),
    OFFICERS_MOVEMENTS_UNIT_MANAGER(510),
    OFFICERS_ALLOWANCES_UNIT_MANAGER(810),
    OFFICERS_SERVICE_TERMINATION_UNIT_MANAGER(85),

    // Soldiers Affairs.
    SOLDIERS_ARCHIVES_UNIT_MANAGER(56),
    SOLDIERS_INFORMATION_UNIT_MANAGER(853),
    SOLDIERS_MOVEMENTS_UNIT_MANAGER(520),
    SOLDIERS_ALLOWANCES_UNIT_MANAGER(820),

    SOLDIERS_INFORMATION_UNIT_VACATIONS_PERSONNEL(30),
    SOLDIERS_FOLLOW_UP_UNIT_VACATIONS_PERSONNEL(40),

    SOLDIERS_SERVICE_TERMINATION_UNIT_MANAGER(90),
    // Civilians Affairs.
    PERSONS_UNIT_MANAGER(60),
    USERS_WAGES_UNIT_MANAGER(70),
    CONTRACTORS_UNIT_MANAGER(80),
    CIVILIANS_ALLOWANCES_UNIT_MANAGER(830),

    // Medical Affairs.
    OFFICERS_MEDICAL_UNIT_VACATIONS_PERSONNEL(57),
    SOLDIERS_MEDICAL_UNIT_VACATIONS_PERSONNEL(58),

    // Security Unit.
    SECURITY_UNIT_MOVEMENTS_PERSONNEL(910),
    SOLDIERS_SECURITY_UNIT_VACATIONS_PERSONNEL(55),

    // Planning and Organization Unit.
    ORGANIZATION_MANPOWER_UNIT_MANAGER(91),
    ORGANIZATION_ADMINISTRATIVE_UNIT_MANAGER(190),
    PLANNING_MANPOWER_UNIT_MANAGER(92),

    // Training Unit
    TRAINING_PLANNING_UNIT_MANAGER(1010),
    INTERNAL_TRAINING_UNIT_MANAGER(1020),
    EXTERNAL_TRAINING_UNIT_MANAGER(1030),
    POST_GRADUATE_SCHOLARSHIP_REPRESENTATIVE(1040),
    PROGRAMS_CURRICULUM_UNIT_MANAGER(1050),
    PROGRAMS_CURRICULUM_COMMITTEE_PRESIDENT(1060),
    // Regions Positions.
    REGION_OFFICERS_AFFAIRS_UNIT_MANAGER(100),
    REGION_SOLDIERS_AFFAIRS_UNIT_MANAGER(118),
    REGION_CIVILIANS_AFFAIRS_UNIT_MANAGER(109),

    REGION_PAYROLL_UNIT_MANAGER(900),

    RETIREMENT_AFFAIRS_UNIT_MANAGER(920),

    REGION_PLANNING_ORGANIZATION_UNIT_MANAGER(93),

    REGION_TRAINING_UNIT_MANAGER(1000);

    private int code;

    private WFPositionsEnum(int code) {
	this.code = code;
    }

    public int getCode() {
	return code;
    }
}
