
package com.code.integration.webservicesclients.filenetclient;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.code.services.config.ETRConfigurationService;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FNAttachmentServicesImplService",
	targetNamespace = "http://services.archms.fg.com/",
	wsdlLocation = "http://vmr8110.ejada.com:9080/FGFNWS/FNAttachmentServicesImplService/WEB-INF/wsdl/FNAttachmentServicesImplService.wsdl")
public class FNAttachmentServicesImplService
	extends Service {

    private final static URL FNATTACHMENTSERVICESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FNATTACHMENTSERVICESIMPLSERVICE_EXCEPTION;
    private final static QName FNATTACHMENTSERVICESIMPLSERVICE_QNAME = new QName("http://services.archms.fg.com/", "FNAttachmentServicesImplService");

    static {
	URL url = null;
	WebServiceException e = null;
	try {
	    url = new URL(ETRConfigurationService.getFileNetWsdlLocation());
	} catch (MalformedURLException ex) {
	    e = new WebServiceException(ex);
	}
	FNATTACHMENTSERVICESIMPLSERVICE_WSDL_LOCATION = url;
	FNATTACHMENTSERVICESIMPLSERVICE_EXCEPTION = e;
    }

    public FNAttachmentServicesImplService() {
	super(__getWsdlLocation(), FNATTACHMENTSERVICESIMPLSERVICE_QNAME);
    }

    public FNAttachmentServicesImplService(WebServiceFeature... features) {
	super(__getWsdlLocation(), FNATTACHMENTSERVICESIMPLSERVICE_QNAME, features);
    }

    public FNAttachmentServicesImplService(URL wsdlLocation) {
	super(wsdlLocation, FNATTACHMENTSERVICESIMPLSERVICE_QNAME);
    }

    public FNAttachmentServicesImplService(URL wsdlLocation, WebServiceFeature... features) {
	super(wsdlLocation, FNATTACHMENTSERVICESIMPLSERVICE_QNAME, features);
    }

    public FNAttachmentServicesImplService(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
    }

    public FNAttachmentServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
	super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns FNAttachmentsServices
     */
    @WebEndpoint(name = "FNAttachmentServicesImplPort")
    public FNAttachmentsServices getFNAttachmentServicesImplPort() {
	return super.getPort(new QName("http://services.archms.fg.com/", "FNAttachmentServicesImplPort"), FNAttachmentsServices.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns FNAttachmentsServices
     */
    @WebEndpoint(name = "FNAttachmentServicesImplPort")
    public FNAttachmentsServices getFNAttachmentServicesImplPort(WebServiceFeature... features) {
	return super.getPort(new QName("http://services.archms.fg.com/", "FNAttachmentServicesImplPort"), FNAttachmentsServices.class, features);
    }

    private static URL __getWsdlLocation() {
	if (FNATTACHMENTSERVICESIMPLSERVICE_EXCEPTION != null) {
	    throw FNATTACHMENTSERVICESIMPLSERVICE_EXCEPTION;
	}
	return FNATTACHMENTSERVICESIMPLSERVICE_WSDL_LOCATION;
    }

}
