package com.code.enums;

/**
 * This enumeration contains all the menu actions that will be used at the application for granting special privileges for users
 * <p>
 * Naming convention as follows:<br>
 * Constant: Module abbreviation + "_" + Screen name + "_" + action name<br>
 * Value: "ETR_HCM_" + Module abbreviation + "_" + Screen name + "_" + action name (Except ETR actions ETR_ not ETR_HCM_).
 */
public enum MenuActionsEnum {

    ETR_DECISION_TEMPLATES_ADMIN("ETR_DECISION_TEMPLATES_ADMIN"),
    ETR_SIGNATURES_MANAGEMENT_ADMIN("ETR_SIGNATURES_MANAGEMENT_ADMIN"),
    ETR_SYSTEM_CONFIGURATIONS_ADMIN("ETR_SYSTEM_CONFIGURATIONS_ADMIN"),

    WF_INBOX_OUTBOX_ADMIN_OFFICERS("ETR_HCM_WF_INBOX_OUTBOX_ADMIN_OFFICERS"),
    WF_INBOX_OUTBOX_ADMIN_SOLDIERS("ETR_HCM_WF_INBOX_OUTBOX_ADMIN_SOLDIERS"),
    WF_INBOX_OUTBOX_ADMIN_CIVILIANS("ETR_HCM_WF_INBOX_OUTBOX_ADMIN_CIVILIANS"),
    WF_SEND_NOTIFICATION_MESSAGES("ETR_HCM_WF_SEND_NOTIFICATION_MESSAGES"),

    VAC_CONFIGURATIONS_MODIFY("ETR_HCM_VAC_CONFIGURATIONS_MODIFY"),

    VAC_BALANCE_INQUIRY_SHOW_ALL_OFFICERS("ETR_HCM_VAC_BALANCE_INQUIRY_SHOW_ALL_OFFICERS"),
    VAC_BALANCE_INQUIRY_SHOW_ALL_SOLDIERS("ETR_HCM_VAC_BALANCE_INQUIRY_SHOW_ALL_SOLDIERS"),
    VAC_BALANCE_INQUIRY_SHOW_ALL_CIVILIANS("ETR_HCM_VAC_BALANCE_INQUIRY_SHOW_ALL_CIVILIANS"),

    VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_OFFICERS("ETR_HCM_VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_OFFICERS"),
    VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_SOLDIERS("ETR_HCM_VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_SOLDIERS"),
    VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_EMPLOYEES("ETR_HCM_VAC_VACATIONS_SEARCH_SHOW_ALL_UNITS_VACATION_PERCENTAGE_ALL_EMPLOYEES"),

    VAC_VACATION_REQUEST_ALL_OFFICERS("ETR_HCM_VAC_VACATION_REQUEST_ALL_OFFICERS"),
    VAC_VACATION_REQUEST_ALL_SOLDIERS("ETR_HCM_VAC_VACATION_REQUEST_ALL_SOLDIERS"),
    VAC_VACATION_REQUEST_ALL_EMPLOYEES("ETR_HCM_VAC_VACATION_REQUEST_ALL_EMPLOYEES"),

    VAC_VACATIONS_REPORTS_FOR_ALL("ETR_HCM_VAC_VACATIONS_REPORTS_FOR_ALL"),

    VAC_HISTORICAL_VACATIONS_OFFICERS("ETR_HCM_HISTORICAL_VAC_FOR_OFFICERS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_SOLDIERS("ETR_HCM_HISTORICAL_VAC_FOR_SOLDIERS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_PERSONS("ETR_HCM_HISTORICAL_VAC_FOR_PERSONS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_USERS("ETR_HCM_HISTORICAL_VAC_FOR_USERS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_WAGES("ETR_HCM_HISTORICAL_VAC_FOR_WAGES_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_CONTRACTORS("ETR_HCM_HISTORICAL_VAC_FOR_CONTRACTORS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_MEDICAL_STAFF("ETR_HCM_HISTORICAL_VAC_FOR_MEDICAL_STAFF_VACATIONS"),

    VAC_HISTORICAL_VACATIONS_SIGN_OFFICERS("ETR_HCM_HISTORICAL_VAC_FOR_SIGN_OFFICERS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_SIGN_SOLDIERS("ETR_HCM_HISTORICAL_VAC_FOR_SIGN_SOLDIERS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_SIGN_PERSONS("ETR_HCM_HISTORICAL_VAC_FOR_SIGN_PERSONS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_SIGN_USERS("ETR_HCM_HISTORICAL_VAC_FOR_SIGN_USERS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_SIGN_WAGES("ETR_HCM_HISTORICAL_VAC_FOR_SIGN_WAGES_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_SIGN_CONTRACTORS("ETR_HCM_HISTORICAL_VAC_FOR_SIGN_CONTRACTORS_VACATIONS"),
    VAC_HISTORICAL_VACATIONS_SIGN_MEDICAL_STAFF("ETR_HCM_HISTORICAL_VAC_FOR_SIGN_MEDICAL_STAFF_VACATIONS"),

    VAC_FUTURE_VACATIONS_GENEAL_MANAGER("ETR_HCM_FUTURE_VAC_FOR_GENERAL_MANAGER_VACATIONS"),
    VAC_FUTURE_VACATIONS_EXTERNAL_OFFICERS("ETR_HCM_FUTURE_VAC_FOR_EXTERNAL_OFFICERS_VACATIONS"),
    VAC_FUTURE_VACATIONS_EXTERNAL_SOLDIERS("ETR_HCM_FUTURE_VAC_FOR_EXTERNAL_SOLDIERS_VACATIONS"),
    VAC_FUTURE_VACATIONS_EXTERNAL_PERSONS("ETR_HCM_FUTURE_VAC_FOR_EXTERNAL_PERSONS_VACATIONS"),
    VAC_FUTURE_VACATIONS_EXTERNAL_USERS("ETR_HCM_FUTURE_VAC_FOR_EXTERNAL_USERS_VACATIONS"),
    VAC_FUTURE_VACATIONS_EXTERNAL_WAGES("ETR_HCM_FUTURE_VAC_FOR_EXTERNAL_WAGES_VACATIONS"),
    VAC_FUTURE_VACATIONS_EXTERNAL_CONTRACTORS("ETR_HCM_FUTURE_VAC_FOR_EXTERNAL_CONTRACTORS_VACATIONS"),
    VAC_FUTURE_VACATIONS_EXTERNAL_MEDICAL_STAFF("ETR_HCM_FUTURE_VAC_FOR_EXTERNAL_MEDICAL_STAFF_VACATIONS"),

    VAC_FUTURE_VACATIONS_SIGN_EXTERNAL_WAGES("ETR_HCM_FUTURE_VAC_FOR_SIGN_EXTERNAL_WAGES_VACATIONS"),
    VAC_FUTURE_VACATIONS_SIGN_GENEAL_MANAGER("ETR_HCM_FUTURE_VAC_FOR_SIGN_GENERAL_MANAGER_VACATIONS"),
    VAC_FUTURE_VACATIONS_SIGN_EXTERNAL_OFFICERS("ETR_HCM_FUTURE_VAC_FOR_SIGN_EXTERNAL_OFFICERS_VACATIONS"),
    VAC_FUTURE_VACATIONS_SIGN_EXTERNAL_SOLDIERS("ETR_HCM_FUTURE_VAC_FOR_SIGN_EXTERNAL_SOLDIERS_VACATIONS"),
    VAC_FUTURE_VACATIONS_SIGN_EXTERNAL_PERSONS("ETR_HCM_FUTURE_VAC_FOR_SIGN_EXTERNAL_PERSONS_VACATIONS"),
    VAC_FUTURE_VACATIONS_SIGN_EXTERNAL_USERS("ETR_HCM_FUTURE_VAC_FOR_SIGN_EXTERNAL_USERS_VACATIONS"),
    VAC_FUTURE_VACATIONS_SIGN_EXTERNAL_CONTRACTORS("ETR_HCM_FUTURE_VAC_FOR_SIGN_EXTERNAL_CONTRACTORS_VACATIONS"),
    VAC_FUTURE_VACATIONS_SIGN_EXTERNAL_MEDICAL_STAFF("ETR_HCM_FUTURE_VAC_FOR_SIGN_EXTERNAL_MEDICAL_STAFF_VACATIONS"),

    VAC_REGULAR_REQUEST_BENF_OFFICERS("ETR_HCM_VAC_REGULAR_REQUEST_ALL_BENF_OFFICERS"),
    VAC_REGULAR_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_REGULAR_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_REGULAR_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_REGULAR_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_REGULAR_MODIFY_REQUEST_BENF_OFFICERS("ETR_HCM_MODIFY_VAC_REGULAR_REQUEST_ALL_BENF_OFFICERS"),
    VAC_REGULAR_MODIFY_REQUEST_BENF_SOLDIERS("ETR_HCM_MODIFY_VAC_REGULAR_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_REGULAR_MODIFY_REQUEST_BENF_EMPLOYEES("ETR_HCM_MODIFY_VAC_REGULAR_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_REGULAR_CANCEL_REQUEST_BENF_OFFICERS("ETR_HCM_CANCEL_VAC_REGULAR_REQUEST_ALL_BENF_OFFICERS"),
    VAC_REGULAR_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_REGULAR_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_REGULAR_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_REGULAR_REQUEST_ALL_BENF_EMPLOYEES"),

    VAC_COMPELLING_REQUEST_BENF_OFFICERS("ETR_HCM_VAC_COMPELLING_REQUEST_ALL_BENF_OFFICERS"),
    VAC_COMPELLING_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_COMPELLING_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_COMPELLING_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_COMPELLING_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_COMPELLING_REQUEST_BENF_CONTRACTORS_WITHOUT_SALARY("ETR_HCM_VAC_COMPELLING_REQUEST_ALL_BENF_CONTRACTORS_WITHOUT_SALARY"),
    VAC_COMPELLING_CANCEL_REQUEST_BENF_OFFICERS("ETR_HCM_CANCEL_VAC_COMPELLING_REQUEST_ALL_BENF_OFFICERS"),
    VAC_COMPELLING_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_COMPELLING_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_COMPELLING_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_COMPELLING_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_COMPELLING_CANCEL_REQUEST_BENF_CONTRACTORS_WITHOUT_SALARY("ETR_HCM_CANCEL_VAC_COMPELLING_REQUEST_ALL_BENF_CONTRACTORS_WITHOUT_SALARY"),

    VAC_SICK_REQUEST_BENF_OFFICERS("ETR_HCM_VAC_SICK_REQUEST_ALL_BENF_OFFICERS"),
    VAC_SICK_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_SICK_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_WORK_INJURY_SICK_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_WORK_INJURY_SICK_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_SICK_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_SICK_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_SICK_MODIFY_REQUEST_BENF_OFFICERS("ETR_HCM_MODIFY_VAC_SICK_REQUEST_ALL_BENF_OFFICERS"),
    VAC_SICK_MODIFY_REQUEST_BENF_SOLDIERS("ETR_HCM_MODIFY_VAC_SICK_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_WORK_INJURY_SICK_MODIFY_REQUEST_BENF_SOLDIERS("ETR_HCM_MODIFY_VAC_WORK_INJURY_SICK_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_SICK_MODIFY_REQUEST_BENF_EMPLOYEES("ETR_HCM_MODIFY_VAC_SICK_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_SICK_CANCEL_REQUEST_BENF_OFFICERS("ETR_HCM_CANCEL_VAC_SICK_REQUEST_ALL_BENF_OFFICERS"),
    VAC_SICK_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_SICK_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_WORK_INJURY_SICK_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_WORK_INJURY_SICK_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_SICK_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_SICK_REQUEST_ALL_BENF_EMPLOYEES"),

    VAC_FIELD_REQUEST_BENF_OFFICERS("ETR_HCM_VAC_FIELD_REQUEST_ALL_BENF_OFFICERS"),
    VAC_FIELD_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_FIELD_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_FIELD_CANCEL_REQUEST_BENF_OFFICERS("ETR_HCM_CANCEL_VAC_FIELD_REQUEST_ALL_BENF_OFFICERS"),
    VAC_FIELD_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_FIELD_REQUEST_ALL_BENF_SOLDIERS"),

    VAC_EXCEPTIONAL_REQUEST_BENF_OFFICERS("ETR_HCM_VAC_EXCEPTIONAL_REQUEST_ALL_BENF_OFFICERS"),
    VAC_EXCEPTIONAL_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_EXCEPTIONAL_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_EXCEPTIONAL_FOR_CIRCUMSTANCES_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_EXCEPTIONAL_FOR_CIRCUMSTANCES_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_EXCEPTIONAL_FOR_ACCOMPANY_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_EXCEPTIONAL_FOR_ACCOMPANY_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_EXCEPTIONAL_CANCEL_REQUEST_BENF_OFFICERS("ETR_HCM_CANCEL_VAC_EXCEPTIONAL_REQUEST_ALL_BENF_OFFICERS"),
    VAC_EXCEPTIONAL_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_EXCEPTIONAL_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_EXCEPTIONAL_FOR_CIRCUMSTANCES_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_EXCEPTIONAL_FOR_CIRCUMSTANCES_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_EXCEPTIONAL_FOR_ACCOMPANY_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_EXCEPTIONAL_FOR_ACCOMPANY_REQUEST_ALL_BENF_EMPLOYEES"),

    VAC_ACCOMPANY_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_ACCOMPANY_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_ACCOMPANY_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_ACCOMPANY_REQUEST_ALL_BENF_EMPLOYEES"),

    VAC_STUDY_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_STUDY_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_EXAM_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_EXAM_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_EXAM_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_EXAM_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_MATERNITY_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_MATERNITY_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_MATERNITY_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_MATERNITY_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_MOTHERHOOD_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_MOTHERHOOD_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_MOTHERHOOD_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_MOTHERHOOD_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_DEATH_WAITING_PERIOD_REQUEST_BENF_SOLDIERS("ETR_HCM_VAC_DEATH_WAITING_PERIOD_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_DEATH_WAITING_PERIOD_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_DEATH_WAITING_PERIOD_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_RELIEF_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_RELIEF_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_SPORTIVE_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_SPORTIVE_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_CULTURAL_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_CULTURAL_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_SOCIAL_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_SOCIAL_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_COMPENSATION_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_COMPENSATION_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_ORPHAN_CARE_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_ORPHAN_CARE_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_DEATH_OF_RELATIVE_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_DEATH_OF_RELATIVE_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_NEW_BABY_REQUEST_BENF_EMPLOYEES("ETR_HCM_VAC_NEW_BABY_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_STUDY_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_STUDY_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_EXAM_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_EXAM_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_EXAM_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_EXAM_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_MATERNITY_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_MATERNITY_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_MATERNITY_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_MATERNITY_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_MOTHERHOOD_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_MOTHERHOOD_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_MOTHERHOOD_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_MOTHERHOOD_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_DEATH_WAITING_PERIOD_CANCEL_REQUEST_BENF_SOLDIERS("ETR_HCM_CANCEL_VAC_DEATH_WAITING_PERIOD_REQUEST_ALL_BENF_SOLDIERS"),
    VAC_DEATH_WAITING_PERIOD_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_DEATH_WAITING_PERIOD_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_RELIEF_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_RELIEF_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_SPORTIVE_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_SPORTIVE_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_CULTURAL_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_CULTURAL_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_SOCIAL_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_SOCIAL_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_COMPENSATION_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_COMPENSATION_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_ORPHAN_CARE_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_ORPHAN_CARE_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_DEATH_OF_RELATIVE_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_DEATH_OF_RELATIVE_REQUEST_ALL_BENF_EMPLOYEES"),
    VAC_NEW_BABY_CANCEL_REQUEST_BENF_EMPLOYEES("ETR_HCM_CANCEL_VAC_NEW_BABY_REQUEST_ALL_BENF_EMPLOYEES"),

    JOBS_REPORTS_SHOW_JOBS_IN_TRANSACTIONS_REPORTS("ETR_HCM_JOBS_REPORTS_SHOW_JOBS_IN_TRANSACTIONS_REPORTS"),
    JOBS_BALANCES_MODIFY("ETR_HCM_JOBS_BALANCES_MODIFY"),
    JOBS_RANKS_POWER_MANAGMENT_MODIFY("ETR_HCM_RANKS_POWER_MANAGMENT_MODIFY"),

    PRS_EMPS_INQUIRY_MALE_SOLDIERS("ETR_HCM_PRS_EMPS_INQUIRY_MALE_SOLDIERS"),
    PRS_EMPS_INQUIRY_FEMALE_SOLDIERS("ETR_HCM_PRS_EMPS_INQUIRY_FEMALE_SOLDIERS"),
    PRS_EMPS_INQUIRY_MALE_CIVILIANS("ETR_HCM_PRS_EMPS_INQUIRY_MALE_CIVILIANS"),
    PRS_EMPS_INQUIRY_FEMALE_CIVILIANS("ETR_HCM_PRS_EMPS_INQUIRY_FEMALE_CIVILIANS"),

    PRS_EMPS_DATA_VIEW_MODIFY_OFFICERS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_OFFICERS"),
    PRS_EMPS_DATA_VIEW_MODIFY_SOLDIERS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_SOLDIERS"),
    PRS_EMPS_DATA_VIEW_MODIFY_FEMALE_SOLDIERS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_FEMALE_SOLDIERS"),
    PRS_EMPS_DATA_VIEW_MODIFY_CIVILIANS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_CIVILIANS"),
    PRS_EMPS_DATA_VIEW_MODIFY_FEMALE_CIVILIANS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_FEMALE_CIVILIANS"),
    PRS_EMPS_DATA_VIEW_SHOW_OFFICERS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_OFFICERS"),
    PRS_EMPS_DATA_VIEW_SHOW_SOLDIERS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_SOLDIERS"),
    PRS_EMPS_DATA_VIEW_SHOW_FEMALE_SOLDIERS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_FEMALE_SOLDIERS"),
    PRS_EMPS_DATA_VIEW_SHOW_CIVILIANS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_CIVILIANS"),
    PRS_EMPS_DATA_VIEW_SHOW_FEMALE_CIVILIANS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_FEMALE_CIVILIANS"),
    PRS_EMPS_DATA_VIEW_SHOW_COMMUNICATIONS("ETR_HCM_PRS_EMPS_DATA_VIEW_SHOW_COMMUNICATIONS"),
    PRS_EMPS_DATA_VIEW_MODIFY_COMMUNICATIONS("ETR_HCM_PRS_EMPS_DATA_VIEW_MODIFY_COMMUNICATIONS"),

    PRS_EMPS_DATA_REPORTS_VIEW_ALL_OFFICERS("ETR_HCM_PRS_EMPS_DATA_REPORTS_VIEW_ALL_OFFICERS"),
    PRS_EMPS_DATA_REPORTS_VIEW_ALL_SOLDIERS("ETR_HCM_PRS_EMPS_DATA_REPORTS_VIEW_ALL_SOLDIERS"),
    PRS_EMPS_DATA_REPORTS_VIEW_ALL_CIVILIANS("ETR_HCM_PRS_EMPS_DATA_REPORTS_VIEW_ALL_CIVILIANS"),

    PRS_EMPS_FILE_MODIFY_OFFICERS("ETR_HCM_PRS_EMPS_FILE_MODIFY_OFFICERS"),
    PRS_EMPS_FILE_MODIFY_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_MODIFY_SOLDIERS"),
    PRS_EMPS_FILE_MODIFY_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_MODIFY_CIVILIANS"),
    PRS_EMPS_FILE_MODIFY_MALE_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_MODIFY_MALE_SOLDIERS"),
    PRS_EMPS_FILE_MODIFY_MALE_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_MODIFY_MALE_CIVILIANS"),
    PRS_EMPS_FILE_MODIFY_FEMALE_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_MODIFY_FEMALE_SOLDIERS"),
    PRS_EMPS_FILE_MODIFY_FEMALE_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_MODIFY_FEMALE_CIVILIANS"),
    PRS_EMPS_FILE_VIEW_OFFICERS("ETR_HCM_PRS_EMPS_FILE_VIEW_OFFICERS"),
    PRS_EMPS_FILE_VIEW_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_VIEW_SOLDIERS"),
    PRS_EMPS_FILE_VIEW_FEMALE_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_VIEW_FEMALE_SOLDIERS"),
    PRS_EMPS_FILE_VIEW_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_VIEW_CIVILIANS"),
    PRS_EMPS_FILE_VIEW_FEMALE_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_VIEW_FEMALE_CIVILIANS"),

    PRS_EMPS_FILE_REPORT_SHOW_OFFICERS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_OFFICERS"),
    PRS_EMPS_FILE_REPORT_SHOW_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_SOLDIERS"),
    PRS_EMPS_FILE_REPORT_SHOW_FEMALE_SOLDIERS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_FEMALE_SOLDIERS"),
    PRS_EMPS_FILE_REPORT_SHOW_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_CIVILIANS"),
    PRS_EMPS_FILE_REPORT_SHOW_FEMALE_CIVILIANS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_FEMALE_CIVILIANS"),
    PRS_EMPS_FILE_REPORT_SHOW_EMPLOYEE_STATUS("ETR_HCM_PRS_EMPS_FILE_REPORT_SHOW_EMPLOYEE_STATUS"),

    PRS_EMPS_PHOTOS_MODIFY_OFFICERS("ETR_HCM_PRS_EMPS_PHOTOS_MODIFY_OFFICERS"),
    PRS_EMPS_PHOTOS_MODIFY_MALE_SOLDIERS("ETR_HCM_PRS_EMPS_PHOTOS_MODIFY_MALE_SOLDIERS"),
    PRS_EMPS_PHOTOS_MODIFY_FEMALE_SOLDIERS("ETR_HCM_PRS_EMPS_PHOTOS_MODIFY_FEMALE_SOLDIERS"),
    PRS_EMPS_PHOTOS_MODIFY_MALE_CIVILLIANS("ETR_HCM_PRS_EMPS_PHOTOS_MODIFY_MALE_CIVILLIANS"),
    PRS_EMPS_PHOTOS_MODIFY_FEMALE_CIVILLIANS("ETR_HCM_PRS_EMPS_PHOTOS_MODIFY_FEMALE_CIVILLIANS"),

    PRS_ADDITIONAL_SPECS_MVT_BLACKLIST("ETR_HCM_PRS_ADDITIONAL_SPECS_MVT_BLACKLIST"),
    PRS_ADDITIONAL_SPECS_MVT_UNBLACKLIST("ETR_HCM_PRS_ADDITIONAL_SPECS_MVT_UNBLACKLIST"),

    REC_EMPS_REGISTRATION_SHOW_OFFICERS("ETR_HCM_REC_EMPS_REGISTRATION_SHOW_OFFICERS"),
    REC_EMPS_REGISTRATION_SHOW_SOLDIERS("ETR_HCM_REC_EMPS_REGISTRATION_SHOW_SOLDIERS"),
    REC_EMPS_REGISTRATION_SHOW_FEMALE_SOLDIERS("ETR_HCM_REC_EMPS_REGISTRATION_SHOW_FEMALE_SOLDIERS"),
    REC_EMPS_REGISTRATION_SHOW_CIVILIANS("ETR_HCM_REC_EMPS_REGISTRATION_SHOW_CIVILIANS"),
    REC_EMPS_REGISTRATION_SHOW_FEMALE_CIVILIANS("ETR_HCM_REC_EMPS_REGISTRATION_SHOW_FEMALE_CIVILIANS"),
    REC_EMPS_REGISTRATION_INSERT_OFFICERS("ETR_HCM_REC_EMPS_REGISTRATION_INSERT_OFFICERS"),
    REC_EMPS_REGISTRATION_INSERT_SOLDIERS("ETR_HCM_REC_EMPS_REGISTRATION_INSERT_SOLDIERS"),
    REC_EMPS_REGISTRATION_INSERT_CIVILIANS("ETR_HCM_REC_EMPS_REGISTRATION_INSERT_CIVILIANS"),
    REC_EMPS_REGISTRATION_MODIFY_OFFICERS("ETR_HCM_REC_EMPS_REGISTRATION_MODIFY_OFFICERS"),
    REC_EMPS_REGISTRATION_MODIFY_SOLDIERS("ETR_HCM_REC_EMPS_REGISTRATION_MODIFY_SOLDIERS"),
    REC_EMPS_REGISTRATION_MODIFY_FEMALE_SOLDIERS("ETR_HCM_REC_EMPS_REGISTRATION_MODIFY_FEMALE_SOLDIERS"),
    REC_EMPS_REGISTRATION_MODIFY_CIVILIANS("ETR_HCM_REC_EMPS_REGISTRATION_MODIFY_CIVILIANS"),
    REC_EMPS_REGISTRATION_MODIFY_FEMALE_CIVILIANS("ETR_HCM_REC_EMPS_REGISTRATION_MODIFY_FEMALE_CIVILIANS"),
    REC_RECRUITMENT_WISHES_MODIFY("ETR_HCM_REC_RECRUITMENT_WISHES_MODIFY"),

    // MVT Menu Actions
    MVT_INTERNAL_ASSIGNMENT_MANAGER_OFFICERS("ETR_HCM_MVT_INTERNAL_ASSIGNMENT_MANAGER_OFFICERS"),
    MVT_INTERNAL_ASSIGNMENT_MANAGER_SOLDIERS("ETR_HCM_MVT_INTERNAL_ASSIGNMENT_MANAGER_SOLDIERS"),
    MVT_INTERNAL_ASSIGNMENT_MANAGER_CIVILIANS("ETR_HCM_MVT_INTERNAL_ASSIGNMENT_MANAGER_CIVILIANS"),
    MVT_MOVE_WISHES_ADMIN("ETR_HCM_MVT_MOVE_WISHES_ADMIN"),
    MVT_BYPASS_MIN_MONTHS_RULE("ETR_HCM_MVT_BYPASS_MIN_MONTHS_RULE"),
    // MSN Menu Actions
    MSN_BALANCE_INQUIRY_SHOW_ALL_OFFICERS("ETR_HCM_MSN_BALANCE_INQUIRY_SHOW_ALL_OFFICERS"),
    MSN_BALANCE_INQUIRY_SHOW_ALL_SOLDIERS("ETR_HCM_MSN_BALANCE_INQUIRY_SHOW_ALL_SOLDIERS"),
    MSN_BALANCE_INQUIRY_SHOW_ALL_PERSONS("ETR_HCM_MSN_BALANCE_INQUIRY_SHOW_ALL_PERSONS"),
    MSN_REQUEST_SEND_ALL_OFFICERS("ETR_HCM_MSN_REQUEST_SEND_ALL_OFFICERS"),
    MSN_REQUEST_SEND_ALL_SOLDIERS("ETR_HCM_MSN_REQUEST_SEND_ALL_SOLDIERS"),
    MSN_REQUEST_SEND_ALL_PERSONS("ETR_HCM_MSN_REQUEST_SEND_ALL_PERSONS"),
    MSN_INQUIRY_REPORT("ETR_HCM_MISSION_STATISTICAL_REPORT_INQUIRY"),

    // PRM Menu Actions
    PRM_OFFICER_REPORT_BRIGADIER_PROMOTE("ETR_HCM_PRM_OFFICER_REPORT_BRIGADIER_PROMOTE"),
    PRM_DECISION_SOLDIERS_CANCELLATION("ETR_HCM_PRM_DECISION_SOLDIERS_CANCELLATION"),

    // DEF LETTER Menu Actions
    DEF_LETTERS_SHOW_ALL_OFFICERS("ETR_HCM_DEFINITION_LETTERS_SHOW_ALL_OFFICERS"),
    DEF_LETTERS_SHOW_ALL_SOLDIERS("ETR_HCM_DEFINITION_LETTERS_SHOW_ALL_SOLDIERS"),
    DEF_LETTERS_SHOW_ALL_EMPLOYEES("ETR_HCM_DEFINITION_LETTERS_SHOW_ALL_EMPLOYEES"),

    // Training - Menu actions
    TRN_MILITARY_COURSES_INSERT_MODIFY("ETR_HCM_TRN_MILITARY_COURSES_INSERT_MODIFY"),
    TRN_EMPLOYEE_TRAINING_FILE_MODIFY("ETR_HCM_TRN_EMPLOYEE_TRAINING_FILE_MODIFY"),
    TRN_EMPLOYEE_TRAINING_FILE_DELETE_CLAIM("TRN_EMPLOYEE_TRAINING_FILE_DELETE_CLAIM"),
    TRN_CLAIMS_REQUEST("ETR_HCM_TRN_CLAIMS_REQUEST"),
    TRN_MILITARY_REQUEST_REGION_ADMIN("ETR_HCM_TRN_MILITARY_REQUEST_REGION_ADMIN"),
    TRN_UNIT_SPECIALIST("ETR_HCM_TRN_UNIT_SPECIALIST"),
    TRN_EMPLOYEES_TRAINING_TRANSACTIONS_INQUIRY_ADMIN("ETR_HCM_TRN_EMPLOYEES_TRAINING_TRANSACTIONS_INQUIRY_ADMIN"),
    TRN_MILITARY_COURSES_INSERT_MODIFY_ATTACHMENTS("ETR_HCM_TRN_MILITARY_COURSES_INSERT_MODIFY_ATTACHMENTS"),
    TRN_TRAINING_PLAN_DETAILS_EXCEL_PRINT("ETR_HCM_TRN_TRAINING_PLAN_DETAILS_EXCEL_PRINT"),
    // Martyrs - Menu Actions
    MARTYRS_TRANSACTIONS_DATA_MODIFY_DELETE("ETR_HCM_MARTYRS_DATA_MODIFY_DELETE"),

    RET_DISCLAIMER_REQUEST_CREATE("ETR_HCM_RET_DISCLAIMER_REQUEST_CREATE"),

    // Raises Menu Actions
    RAISES_APPROVE_ANNUAL_RAISE_REGISTRATION("ETR_HCM_RAISES_APPROVE_ANNUAL_RAISE"),
    RAISES_APPROVE_ADDITIONAL_RAISE("ETR_HCM_RAISES_APPROVE_ADDITIONAL_RAISE");

    private String code;

    private MenuActionsEnum(String code) {
	this.code = code;
    }

    public String getCode() {
	return code;
    }
}
