package com.code.enums;

public enum RecruitmentClassesEnum {

    OFFICERS_RECRUITMENT(300),
    SOLDIERS_SOLDIER_OR_FIRST_SOLDIER_RECRUITMENT(310),
    SOLDIERS_CORPORAL_OR_HIGHER_RECRUITMENT(311),
    SOLDIERS_GRADUATION_LETTER_DECISION_RECRUITMENT(312),
    SOLDIERS_SOLDIER_OR_FIRST_SOLDIER_EXCEPTIONAL_RECRUITMENT(313),
    SOLDIERS_CORPORAL_OR_HIGHER_EXCEPTIONAL_RECRUITMENT(314),
    SOLDIERS_GRADUATION_LETTER_DECISION_EXCEPTIONAL_RECRUITMENT(315),
    INSPECTORS_EXCEPTIONAL_RECRUITMENT(316),
    INSPECTORS_RECRUITMENT(317),
    PERSONS_RECRUITMENT(320),
    USERS_RECRUITMENT(330),
    WAGES_RECRUITMENT(340),
    CONTRACTORS_RECRUITMENT(350),
    MEDICAL_STAFF_RECRUITMENT(360);

    private long code;

    private RecruitmentClassesEnum(long code) {
	this.code = code;
    }

    public long getCode() {
	return code;
    }
}
