package com.code.enums;

public enum ReportNamesEnum {

    // UNITS

    UNITS_ORGANIZATION_HIERARCHY("/Reports/Units/UNITS_ORGANIZATION_HIERARCHY.JRXML"),
    UNITS_HIERARCHY_TRANSACTIONS("/Reports/Units/UNITS_HIERARCHY_TRANSACTIONS.JRXML"),
    UNITS_HIERARCHY_TRANSACTIONS_STATISTICAL("/Reports/Units/UNITS_HIERARCHY_TRANSACTIONS_STATISTICAL.JRXML"),
    UNITS_UNIT_TRANSACTIONS("/Reports/Units/UNITS_UNIT_TRANSACTIONS.JRXML"),
    UNITS_REQUIRED_TRANSACTIONS("/Reports/Units/UNITS_REQUIRED_TRANSACTIONS.JRXML"),

    UNITS_ORG_TABLES_LAST_DECISION("/Reports/Units/UNITS_ORG_TABLES_LAST_DECISION.JRXML"),
    UNITS_ORG_TABLES_OFFICIAL("/Reports/Units/UNITS_ORG_TABLES_OFFICIAL.JRXML"),
    UNITS_MEDICAL_STAFF_ORG_TABLES_LAST_DECISION("/Reports/Units/UNITS_MEDICAL_STAFF_ORG_TABLES_LAST_DECISION.JRXML"),
    UNITS_MEDICAL_STAFF_ORG_TABLES_OFFICIAL("/Reports/Units/UNITS_MEDICAL_STAFF_ORG_TABLES_OFFICIAL.JRXML"),

    UNITS_ORG_TARGETS_TASKS("/Reports/Units/UNITS_ORG_TARGETS_TASKS.JRXML"),

    // JOBS

    JOBS_DECISION_OFFICERS_COLLECTIVE("/Reports/Jobs/JOBS_DECISION_OFFICERS_COLLECTIVE.JRXML"),
    JOBS_DECISION_SOLDIERS_COLLECTIVE("/Reports/Jobs/JOBS_DECISION_SOLDIERS_COLLECTIVE.JRXML"),
    JOBS_DECISION_SOLDIERS_COLLECTIVE_RESERVATIONS("/Reports/Jobs/JOBS_DECISION_SOLDIERS_COLLECTIVE_RESERVATIONS.JRXML"),

    JOBS_MINOR_SPECIALIZATION_DESCRIPTION("/Reports/Jobs/JOBS_MINOR_SPECIALIZATION_DESCRIPTION.JRXML"),

    JOBS_DETAILS("/Reports/Jobs/JOBS_DETAILS.JRXML"),
    JOBS_TRANSACTIONS_DETAILS("/Reports/Jobs/JOBS_TRANSACTIONS_DETAILS.JRXML"),
    JOBS_STATISTICAL("/Reports/Jobs/JOBS_STATISTICAL.JRXML"),
    JOBS_IN_TRANSACTIONS("/Reports/Jobs/JOBS_IN_TRANSACTIONS.JRXML"),
    JOBS_IN_TRANSACTIONS_STATISTICAL("/Reports/Jobs/JOBS_IN_TRANSACTIONS_STATISTICAL.JRXML"),
    JOBS_FREEZED_BY_OTHER_SYSTEMS("/Reports/Jobs/JOBS_FREEZED_BY_OTHER_SYSTEMS.JRXML"),

    JOBS_MANPOWER_NEEDS_REQUESTS("/Reports/Jobs/JOBS_MANPOWER_NEEDS_REQUESTS.JRXML"),
    JOBS_MANPOWER_NEEDS_STUDIES_SUMMARY("/Reports/Jobs/JOBS_MANPOWER_NEEDS_STUDIES_SUMMARY.JRXML"),
    JOBS_MANPOWER_NEEDS_STUDIES_DETAILED("/Reports/Jobs/JOBS_MANPOWER_NEEDS_STUDIES_DETAILED.JRXML"),

    // EMPLOYEES

    EMPLOYEES_DATA("/Reports/Employees/EMPLOYEES_DATA.JRXML"),
    EMPLOYEES_OFFICERS_FILE_REPORT("/Reports/Employees/EMPLOYEES_OFFICERS_FILE_REPORT.JRXML"),
    EMPLOYEES_SOLDIERS_FILE_REPORT("/Reports/Employees/EMPLOYEES_SOLDIERS_FILE_REPORT.JRXML"),
    EMPLOYEES_CIVILIANS_FILE_REPORT("/Reports/Employees/EMPLOYEES_CIVILIANS_FILE_REPORT.JRXML"),
    EMPLOYEES_STATISTICS("/Reports/Employees/EMPLOYEES_STATISTICS.JRXML"),
    EMPLOYEES_MEDICAL_STAFF_STATISTICS("/Reports/Employees/EMPLOYEES_MEDICAL_STAFF_STATISTICS.JRXML"),
    EMPLOYEES_QUALIFICATIONS("/Reports/Employees/EMPLOYEES_QUALIFICATIONS.JRXML"),
    EMPLOYEES_ADDITIONAL_SPECIALIZATION("/Reports/Employees/EMPLOYEES_ADDITIONAL_SPECIALIZATION.JRXML"),
    EMPLOYEES_SERVICE_YEARS("/Reports/Employees/EMPLOYEES_SERVICE_YEARS.JRXML"),
    EMPLOYEES_JOB_MODIFIED_FLAG("/Reports/Employees/EMPLOYEES_JOB_MODIFIED_FLAG.JRXML"),
    EMPLOYEES_PHOTOS_STATUSES("/Reports/Employees/EMPLOYEES_PHOTOS_STATUSES.JRXML"),

    // RECRUITMENT

    RECRUITMENT_DECISION_OFFICERS("/Reports/Recruitments/RECRUITMENT_DECISION_OFFICERS.JRXML"),
    RECRUITMENT_DECISION_OFFICERS_COLLECTIVE("/Reports/Recruitments/RECRUITMENT_DECISION_OFFICERS_COLLECTIVE.JRXML"),
    RECRUITMENT_DECISION_SOLIDERS("/Reports/Recruitments/RECRUITMENT_DECISION_SOLIDERS.JRXML"),
    RECRUITMENT_DECISION_SOLIDERS_COLLECTIVE("/Reports/Recruitments/RECRUITMENT_DECISION_SOLIDERS_COLLECTIVE.JRXML"),
    RECRUITMENT_DECISION_SOLDIERS_GRADUATION_LETTER("/Reports/Recruitments/RECRUITMENT_DECISION_SOLDIERS_GRADUATION_LETTER.JRXML"),
    RECRUITMENT_DECISION_SOLDIERS_COLLECTIVE_GRADUATION_LETTER("/Reports/Recruitments/RECRUITMENT_DECISION_SOLDIERS_COLLECTIVE_GRADUATION_LETTER.JRXML"),
    RECRUITMENT_SOLDIERS_COUNT_STATEMENT("/Reports/Recruitments/RECRUITMENT_SOLDIERS_COUNT_STATEMENT.JRXML"),
    RECRUITMENT_DECISION_SOLIDERS_EXCEPTIONAL_AND_INSPECTORS("/Reports/Recruitments/RECRUITMENT_DECISION_SOLIDERS_EXCEPTIONAL_AND_INSPECTORS.JRXML"),
    RECRUITMENT_DECISION_SOLDIERS_INSPECTORS_COLLECTIVE("/Reports/Recruitments/RECRUITMENT_DECISION_SOLDIERS_INSPECTORS_COLLECTIVE.JRXML"),
    RECRUITMENT_DECISION_SOLDIERS_EXECPTIONAL_GRADUATION_LETTER("/Reports/Recruitments/RECRUITMENT_DECISION_SOLDIERS_EXECPTIONAL_GRADUATION_LETTER.JRXML"),
    RECRUITMENT_DECISION_EMPLOYEES("/Reports/Recruitments/RECRUITMENT_DECISION_EMPLOYEES.JRXML"),
    RECRUITMENT_DECISION_EMPLOYEES_COLLECTIVE("/Reports/Recruitments/RECRUITMENT_DECISION_EMPLOYEES_COLLECTIVE.JRXML"),
    RECRUITMENT_DECISION_EMPLOYEES_CONTRACTOR("/Reports/Recruitments/RECRUITMENT_DECISION_EMPLOYEES_CONTRACTOR.JRXML"),
    RECRUITMENT_OFFICERS_UNDER_RECRUITMENT_DATA("/Reports/Recruitments/RECRUITMENT_OFFICERS_UNDER_RECRUITMENT_DATA.JRXML"),
    RECRUITMENT_SOLDIERS_UNDER_RECRUITMENT_AND_DISTRIBUTION_DATA("/Reports/Recruitments/RECRUITMENT_SOLDIERS_UNDER_RECRUITMENT_AND_DISTRIBUTION_DATA.JRXML"),
    RECRUITMENT_SOLDIERS_RECRUITED_STATISTICAL_REPORT("/Reports/Recruitments/RECRUITMENT_SOLDIERS_RECRUITED_STATISTICAL_REPORT.JRXML"),
    RECRUITMENT_SOLDIERS_RECRUITED_DETAILED_REPORT("/Reports/Recruitments/RECRUITMENT_SOLDIERS_RECRUITED_DETAILED_REPORT.JRXML"),

    // TERMINATIONS

    TERMINATIONS_DECISION_SOLDIERS("/Reports/Terminations/Soldiers/TERMINATIONS_DECISION_SOLDIERS.JRXML"),
    TERMINATIONS_DECISION_SOLDIERS_CANCEL_TRANSACTION("/Reports/Terminations/Soldiers/TERMINATIONS_DECISION_SOLDIERS_CANCEL_TRANSACTION.JRXML"),

    TERMINATIONS_DECISION_CIVILIANS("/Reports/Terminations/Civilians/TERMINATIONS_DECISION_CIVILIANS.JRXML"),
    TERMINATIONS_DECISION_CIVILIANS_CANCEL_TRANSACTION("/Reports/Terminations/Civilians/TERMINATIONS_DECISION_CIVILIANS_CANCEL_TRANSACTION.JRXML"),
    TERMINATIONS_DECISION_CIVILIANS_TERMINATION_MOVEMENT("/Reports/Terminations/Civilians/TERMINATIONS_DECISION_CIVILIANS_TERMINATION_MOVEMENT.JRXML"),

    TERMINATIONS_OFFICERS_RECORD("/Reports/Terminations/Officers/TERMINATIONS_OFFICERS_RECORD.JRXML"),
    TERMINATIONS_OFFICERS_RECORD_OTHER_REASONS("/Reports/Terminations/Officers/TERMINATIONS_OFFICERS_RECORD_OTHER_REASONS.JRXML"),
    TERMINATIONS_SOLDIERS_RECORD("/Reports/Terminations/Soldiers/TERMINATIONS_SOLDIERS_RECORD.JRXML"),
    TERMINATIONS_CIVILIANS_RECORD("/Reports/Terminations/Civilians/TERMINATIONS_CIVILIANS_RECORD.JRXML"),

    TERMINATIONS_OFFICERS_RETIREMENT_ELIGIBLE_INQUIRY("/Reports/Terminations/Officers/TERMINATIONS_OFFICERS_RETIREMENT_ELIGIBLE_INQUIRY.JRXML"),
    TERMINATIONS_CIVILIANS_RETIREMENT_ELIGIBLE_INQUIRY("/Reports/Terminations/Civilians/TERMINATIONS_CIVILIANS_RETIREMENT_ELIGIBLE_INQUIRY.JRXML"),
    TERMINATIONS_CONTRACTORS_RECORD("/Reports/Terminations/Civilians/TERMINATIONS_CONTRACTORS_RECORD.JRXML"),
    TERMINATIONS_SOLDIERS_RETIREMENT_ELIGIBLE_INQUIRY("/Reports/Terminations/Soldiers/TERMINATIONS_SOLDIERS_RETIREMENT_ELIGIBLE_INQUIRY.JRXML"),
    TERMINATIONS_SOLDIERS_RETIREMENT_ELIGIBLE_INQUIRY_STATISTICAL("/Reports/Terminations/Soldiers/TERMINATIONS_SOLDIERS_RETIREMENT_ELIGIBLE_INQUIRY_STATISTICAL.JRXML"),

    TERMINATIONS_SERVICE_TERMINATED_INQUIRY("/Reports/Terminations/TERMINATIONS_SERVICE_TERMINATED_INQUIRY.JRXML"),
    TERMINATIONS_SERVICE_TERMINATED_INQUIRY_REGIONS_STATISTICAL("/Reports/Terminations/TERMINATIONS_SERVICE_TERMINATED_INQUIRY_REGIONS_STATISTICAL.JRXML"),
    TERMINATIONS_SERVICE_TERMINATED_INQUIRY_REASONS_STATISTICAL("/Reports/Terminations/TERMINATIONS_SERVICE_TERMINATED_INQUIRY_REASONS_STATISTICAL.JRXML"),
    TERMINATIONS_MEDICAL_STAFF_SERVICE_TERMINATED_INQUIRY_REGIONS_STATISTICAL("/Reports/Terminations/TERMINATIONS_MEDICAL_STAFF_SERVICE_TERMINATED_INQUIRY_REGIONS_STATISTICAL.JRXML"),
    TERMINATIONS_MEDICAL_STAFF_SERVICE_TERMINATED_INQUIRY_REASONS_STATISTICAL("/Reports/Terminations/TERMINATIONS_MEDICAL_STAFF_SERVICE_TERMINATED_INQUIRY_REASONS_STATISTICAL.JRXML"),
    TERMINATIONS_EXTENSION_INQUIRY("/Reports/Terminations/TERMINATIONS_EXTENSION_INQUIRY.JRXML"),
    TERMINATIONS_EXTENSION_INQUIRY_STATISTICAL("/Reports/Terminations/TERMINATIONS_EXTENSION_INQUIRY_STATISTICAL.JRXML"),
    TERMINATIONS_MEDICAL_STAFF_EXTENSION_INQUIRY_STATISTICAL("/Reports/Terminations/TERMINATIONS_MEDICAL_STAFF_EXTENSION_INQUIRY_STATISTICAL.JRXML"),
    RETIREMENTS_DISCLAIMER_STEPS("/Reports/Retirements/RETIREMENTS_DISCLAIMER_STEPS.JRXML"),

    // MOVEMENTS

    MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_MOVE_INTERNAL("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_MOVE_INTERNAL.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_SUBJOIN("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_SUBJOIN.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_MOVE_EXTERNAL("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_MOVE_EXTERNAL.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_MOVE_INTERNAL("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_MOVE_INTERNAL.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_SUBJION("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_SUBJION.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_MOVE_EXTERNAL("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_MOVE_EXTERNAL.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_MOVE_FREEZE_DECISION("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_MOVE_FREEZE_DECISION.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_MOVE_FREEZE_APPENDIX("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_MOVE_FREEZE_APPENDIX.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_SUBJOIN_CANCEL_TERMINATE("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_COLLECTIVE_SUBJOIN_CANCEL_TERMINATE.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_MOVE_EXCHANGE("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_MOVE_EXCHANGE.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_MOVE_FREEZE("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_MOVE_FREEZE.JRXML"),
    MOVEMENTS_DECISION_SOLDIERS_SUBJOIN_CANCEL_TERMINATE("/Reports/Movements/Soldiers/MOVEMENTS_DECISION_SOLDIERS_SUBJOIN_CANCEL_TERMINATE.JRXML"),

    MOVEMENTS_DECISION_OFFICERS_MOVE_INTERNAL("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_MOVE_INTERNAL.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_MOVE_EXCHANGE("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_MOVE_EXCHANGE.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_SUBJOIN("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_SUBJOIN.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_ASSIGNMENT_INTERNAL("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_ASSIGNMENT_INTERNAL.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_ASSIGNMENT_INTERNAL("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_ASSIGNMENT_INTERNAL.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_MOVE_INTERNAL("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_MOVE_INTERNAL.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_SUBJOIN_INTERNAL("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_SUBJOIN_INTERNAL.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_SUBJOIN_INTERNAL_CANCEL("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_SUBJOIN_INTERNAL_CANCEL.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_SUBJOIN_INTERNAL_EXTENSION("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_SUBJOIN_INTERNAL_EXTENSION.JRXML"),
    MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_SUBJOIN_INTERNAL_TERMINATION("/Reports/Movements/Officers/MOVEMENTS_DECISION_OFFICERS_COLLECTIVE_SUBJOIN_INTERNAL_TERMINATION.JRXML"),
    MOVEMENTS_OFFICERS_ASSIGNMENT_TRANSACTIONS("/Reports/Movements/MOVEMENTS_OFFICERS_ASSIGNMENT_TRANSACTIONS.JRXML"),

    MOVEMENTS_DECISION_EMPLOYEES_MOVE_EXCHANGE("/Reports/Movements/Employees/MOVEMENTS_DECISION_EMPLOYEES_MOVE_EXCHANGE.JRXML"),
    MOVEMENTS_DECISION_EMPLOYEES_ASSIGNMENT("/Reports/Movements/Employees/MOVEMENTS_DECISION_EMPLOYEES_ASSIGNMENT.JRXML"),
    MOVEMENTS_DECISION_EMPLOYEES_MOVE("/Reports/Movements/Employees/MOVEMENTS_DECISION_EMPLOYEES_MOVE.JRXML"),
    MOVEMENTS_DECISION_EMPLOYEES_COLLECTIVE_MOVE("/Reports/Movements/Employees/MOVEMENTS_DECISION_EMPLOYEES_COLLECTIVE_MOVE.JRXML"),
    MOVEMENTS_DECISION_EMPLOYEES_COLLECTIVE_ASSIGNMENT("/Reports/Movements/Employees/MOVEMENTS_DECISION_EMPLOYEES_COLLECTIVE_ASSIGNMENT.JRXML"),
    MOVEMENTS_DECISION_EMPLOYEES_COLLECTIVE_ASSIGNMENT_TERMINATION("/Reports/Movements/Employees/MOVEMENTS_DECISION_EMPLOYEES_COLLECTIVE_ASSIGNMENT_TERMINATION.JRXML"),
    MOVEMENTS_DECISION_EMPLOYEES_COLLECTIVE_ASSIGNMENT_CANCELATION("/Reports/Movements/Employees/MOVEMENTS_DECISION_EMPLOYEES_COLLECTIVE_ASSIGNMENT_CANCELATION.JRXML"),

    MOVEMENTS_TRANSACTIONS_STATISTICS("/Reports/Movements/MOVEMENTS_TRANSACTIONS_STATISTICS.JRXML"),
    MOVEMENTS_SUBJOIN_TRANSACTIONS("/Reports/Movements/MOVEMENTS_SUBJOIN_TRANSACTIONS.JRXML"),
    MOVEMENTS_SUBJOIN_TRANSACTIONS_STATISTICS("/Reports/Movements/MOVEMENTS_SUBJOIN_TRANSACTIONS_STATISTICS.JRXML"),
    MOVEMENTS_EXTERNAL_MOVEMENTS_TRANSACTIONS("/Reports/Movements/MOVEMENTS_EXTERNAL_MOVEMENTS_TRANSACTIONS.JRXML"),
    MOVEMENTS_INTERNAL_ASSIGNMENTS_TRANSACTIONS("/Reports/Movements/MOVEMENTS_INTERNAL_ASSIGNMENTS_TRANSACTIONS.JRXML"),
    MOVEMENTS_INTERNAL_MOVES_TRANSACTIONS("/Reports/Movements/MOVEMENTS_INTERNAL_MOVES_TRANSACTIONS.JRXML"),
    MOVEMENTS_INTERNAL_MOVES_TRANSACTIONS_STATISTICS("/Reports/Movements/MOVEMENTS_INTERNAL_MOVES_TRANSACTIONS_STATISTICS.JRXML"),
    MOVEMENTS_SOLDIERS_MOVE_WISHES("/Reports/Movements/MOVEMENTS_SOLDIERS_MOVE_WISHES.JRXML"),

    MOVEMENTS_MOVE_JOINING_DOCUMENT("/Reports/Movements/MOVEMENTS_MOVE_JOINING_DOCUMENT.JRXML"),
    MOVEMENTS_SUBJOIN_JOINING_DOCUMENT("/Reports/Movements/MOVEMENTS_SUBJOIN_JOINING_DOCUMENT.JRXML"),
    MOVEMENTS_SUBJOIN_TRANSACTIONS_ACCORDING_TO_END_DATE("/Reports/Movements/MOVEMENTS_SUBJOIN_TRANSACTIONS_ACCORDING_TO_END_DATE.JRXML"),
    // PROMOTIONS

    PROMOTIONS_DECISION_SOLDIERS("/Reports/Promotions/PROMOTIONS_DECISION_SOLDIERS.JRXML"),
    PROMOTIONS_DECISION_SOLDIERS_COLLECTIVE("/Reports/Promotions/PROMOTIONS_DECISION_SOLDIERS_COLLECTIVE.JRXML"),
    PROMOTIONS_DECISION_SOLDIERS_COLLECTIVE_SCALE_UP("/Reports/Promotions/PROMOTIONS_DECISION_SOLDIERS_COLLECTIVE_SCALE_UP.JRXML"),
    PROMOTIONS_DECISION_CIVILIANS("/Reports/Promotions/PROMOTIONS_DECISION_CIVILIANS.JRXML"),
    PROMOTIONS_SOLDIERS_DECISION_CANCELLATION("/Reports/Promotions/PROMOTIONS_SOLDIERS_DECISION_CANCELLATION.JRXML"),

    PROMOTIONS_OFFICERS_REPORT("/Reports/Promotions/PROMOTIONS_OFFICERS_REPORT.JRXML"),
    PROMOTIONS_OFFICERS_COLLECTIVE_REPORT("/Reports/Promotions/PROMOTIONS_OFFICERS_COLLECTIVE_REPORT.JRXML"),

    PROMOTIONS_PRIME_SERGEANTS_REPORT("/Reports/Promotions/PROMOTIONS_PRIME_SERGEANTS_REPORT.JRXML"),
    PROMOTIONS_PRIME_SERGEANTS_COLLECTIVE_REPORT("/Reports/Promotions/PROMOTIONS_PRIME_SERGEANTS_COLLECTIVE_REPORT.JRXML"),
    PROMOTIONS_PRIME_SERGEANTS_SHOW_REPORT("/Reports/Promotions/PROMOTIONS_PRIME_SERGEANTS_SHOW_REPORT.JRXML"),

    PROMOTIONS_CIVILIANS_COLLECTIVE_REPORT("/Reports/Promotions/PROMOTIONS_CIVILIANS_COLLECTIVE_REPORT.JRXML"),
    PROMOTIONS_CIVILIANS_COLLECTIVE_REPORT_WORD("/Reports/Promotions/PROMOTIONS_CIVILIANS_COLLECTIVE_REPORT_WORD.JRXML"),
    PROMOTIONS_CIVILIANS_COLLECTIVE_UNCANDIDATES_REPORT("/Reports/Promotions/PROMOTIONS_CIVILIANS_COLLECTIVE_UNCANDIDATES_REPORT.JRXML"),
    PROMOTIONS_ELIGIBLE_INQUIRY("/Reports/Promotions/PROMOTIONS_ELIGIBLE_INQUIRY.JRXML"),
    PROMOTIONS_PROMOTED_INQUIRY("/Reports/Promotions/PROMOTIONS_PROMOTED_INQUIRY.JRXML"),
    PROMOTIONS_PROMOTED_STATISTICAL_INQUIRY("/Reports/Promotions/PROMOTIONS_PROMOTED_STATISTICAL_INQUIRY.JRXML"),
    PROMOTIONS_SOLDIERS_ELIGIBLE_STATISTICAL_INQUIRY("/Reports/Promotions/PROMOTIONS_SOLDIERS_ELIGIBLE_STATISTICAL_INQUIRY.JRXML"),
    PROMOTIONS_SOLDIERS_ELIGIBLE_WITH_MOVEMENTS_UNDER_PROCESSING("/Reports/Promotions/PROMOTIONS_SOLDIERS_ELIGIBLE_WITH_MOVEMENTS_UNDER_PROCESSING.JRXML"),
    PROMOTIONS_RANK_POWER_DATA("/Reports/Promotions/PROMOTIONS_RANK_POWER_DATA.JRXML"),
    PROMOTIONS_SOLDIERS_COLLECTIVE_REPORT("/Reports/Promotions/PROMOTIONS_SOLDIERS_COLLECTIVE_REPORT.JRXML"),
    PROMOTIONS_SOLDIERS_CANDIDATES_BY_DIFFERENTIATION("/Reports/Promotions/PROMOTIONS_SOLDIERS_CANDIDATES_BY_DIFFERENTIATION.JRXML"),
    // MISSIONS

    MISSIONS_DECISION_OFFICERS("/Reports/Missions/Officers/MISSIONS_DECISION_OFFICERS.JRXML"),
    MISSIONS_DECISION_OFFICERS_COLLECTIVE("/Reports/Missions/Officers/MISSIONS_DECISION_OFFICERS_COLLECTIVE.JRXML"),
    MISSIONS_OFFICERS_FINANCIAL_LINK_COLLECTIVE("/Reports/Missions/Officers/MISSIONS_OFFICERS_FINANCIAL_LINK_COLLECTIVE.JRXML"),
    MISSIONS_OFFICERS_FINANCIAL_LINK("/Reports/Missions/Officers/MISSIONS_OFFICERS_FINANCIAL_LINK.JRXML"),
    MISSIONS_OFFICERS_PAYMENT("/Reports/Missions/Officers/MISSIONS_OFFICERS_PAYMENT.JRXML"),
    MISSIONS_OFFICERS_PAYMENT_COLLECTIVE("/Reports/Missions/Officers/MISSIONS_OFFICERS_PAYMENT_COLLECTIVE.JRXML"),
    MISSIONS_OFFICERS_BALANCE_INQUIRY("/Reports/Missions/Officers/MISSIONS_OFFICERS_BALANCE_INQUIRY.JRXML"),
    MISSIONS_OFFICERS_DATA("/Reports/Missions/Officers/MISSIONS_OFFICERS_DATA.JRXML"),
    MISSIONS_OFFICERS_DATA_COLLECTIVE("/Reports/Missions/Officers/MISSIONS_OFFICERS_DATA_COLLECTIVE.JRXML"),
    MISSIONS_OFFICERS_OFFICIAL_PERFORMANCE("/Reports/Missions/Officers/MISSIONS_OFFICERS_OFFICIAL_PERFORMANCE.JRXML"),
    MISSIONS_DECISION_SOLDIERS("/Reports/Missions/Soldiers/MISSIONS_DECISION_SOLDIERS.JRXML"),
    MISSIONS_DECISION_SOLDIERS_COLLECTIVE("/Reports/Missions/Soldiers/MISSIONS_DECISION_SOLDIERS_COLLECTIVE.JRXML"),
    MISSIONS_SOLDIERS_PAYMENT("/Reports/Missions/Soldiers/MISSIONS_SOLDIERS_PAYMENT.JRXML"),
    MISSIONS_SOLDIERS_PAYMENT_COLLECTIVE("/Reports/Missions/Soldiers/MISSIONS_SOLDIERS_PAYMENT_COLLECTIVE.JRXML"),
    MISSIONS_SOLDIERS_BALANCE_INQUIRY("/Reports/Missions/Soldiers/MISSIONS_SOLDIERS_BALANCE_INQUIRY.JRXML"),
    MISSIONS_SOLDIERS_DATA("/Reports/Missions/Soldiers/MISSIONS_SOLDIERS_DATA.JRXML"),
    MISSIONS_SOLDIERS_DATA_COLLECTIVE("/Reports/Missions/Soldiers/MISSIONS_SOLDIERS_DATA_COLLECTIVE.JRXML"),
    MISSIONS_SOLDIERS_OFFICIAL_PERFORMANCE("/Reports/Missions/Soldiers/MISSIONS_SOLDIERS_OFFICIAL_PERFORMANCE.JRXML"),
    MISSIONS_DECISION_CIVILIANS("/Reports/Missions/Civilians/MISSIONS_DECISION_CIVILIANS.JRXML"),
    MISSIONS_DECISION_CIVILIANS_COLLECTIVE("/Reports/Missions/Civilians/MISSIONS_DECISION_CIVILIANS_COLLECTIVE.JRXML"),
    MISSIONS_CIVILIANS_BALANCE_INQUIRY("/Reports/Missions/Civilians/MISSIONS_CIVILIANS_BALANCE_INQUIRY.JRXML"),
    MISSIONS_CIVILIANS_DATA("/Reports/Missions/Civilians/MISSIONS_CIVILIANS_DATA.JRXML"),
    MISSIONS_CIVILIANS_DATA_COLLECTIVE("/Reports/Missions/Civilians/MISSIONS_CIVILIANS_DATA_COLLECTIVE.JRXML"),
    MISSIONS_CIVILIANS_OFFICIAL_PERFORMANCE("/Reports/Missions/Civilians/MISSIONS_CIVILIANS_OFFICIAL_PERFORMANCE.JRXML"),
    MISSIONS_STATISICAL_REPORT("/Reports/Missions/MISSIONS_STATISICAL_REPORT.JRXML"),
    MISSIONS_EMPLOYEES_STATISICAL_REPORT("/Reports/Missions/MISSIONS_EMPLOYEES_STATISICAL_REPORT.JRXML"),

    // VACATIONS

    VACATIONS_DECISION_OFFICERS_REGULAR("/Reports/Vacations/VACATIONS_DECISION_OFFICERS_REGULAR.JRXML"),
    VACATIONS_DECISION_OFFICERS_COMPELLING("/Reports/Vacations/VACATIONS_DECISION_OFFICERS_COMPELLING.JRXML"),
    VACATIONS_DECISION_OFFICERS_SICK("/Reports/Vacations/VACATIONS_DECISION_OFFICERS_SICK.JRXML"),
    VACATIONS_DECISION_OFFICERS_FIELD("/Reports/Vacations/VACATIONS_DECISION_OFFICERS_FIELD.JRXML"),
    VACATIONS_DECISION_OFFICERS_EXCEPTIONAL("/Reports/Vacations/VACATIONS_DECISION_OFFICERS_EXCEPTIONAL.JRXML"),

    VACATIONS_DECISION_SOLDIERS_REGULAR("/Reports/Vacations/VACATIONS_DECISION_SOLDIERS_REGULAR.JRXML"),
    VACATIONS_DECISION_SOLDIERS_COMPELLING("/Reports/Vacations/VACATIONS_DECISION_SOLDIERS_COMPELLING.JRXML"),
    VACATIONS_DECISION_SOLDIERS_SICK("/Reports/Vacations/VACATIONS_DECISION_SOLDIERS_SICK.JRXML"),
    VACATIONS_DECISION_SOLDIERS_FIELD("/Reports/Vacations/VACATIONS_DECISION_SOLDIERS_FIELD.JRXML"),
    VACATIONS_DECISION_SOLDIERS_EXCEPTIONAL("/Reports/Vacations/VACATIONS_DECISION_SOLDIERS_EXCEPTIONAL.JRXML"),
    VACATIONS_DECISION_SOLDIERS_MANY_VACATIONS("/Reports/Vacations/VACATIONS_DECISION_SOLDIERS_MANY_VACATIONS.JRXML"),

    VACATIONS_DECISION_CIVILIANS_REGULAR("/Reports/Vacations/VACATIONS_DECISION_CIVILIANS_REGULAR.JRXML"),
    VACATIONS_DECISION_CIVILIANS_COMPELLING("/Reports/Vacations/VACATIONS_DECISION_CIVILIANS_COMPELLING.JRXML"),
    VACATIONS_DECISION_CIVILIANS_SICK("/Reports/Vacations/VACATIONS_DECISION_CIVILIANS_SICK.JRXML"),
    VACATIONS_DECISION_CIVILIANS_ACCOMPANY("/Reports/Vacations/VACATIONS_DECISION_CIVILIANS_ACCOMPANY.JRXML"),
    VACATIONS_DECISION_CIVILIANS_EXCEPTIONAL("/Reports/Vacations/VACATIONS_DECISION_CIVILIANS_EXCEPTIONAL.JRXML"),
    VACATIONS_DECISION_CIVILIANS_MANY_VACATIONS("/Reports/Vacations/VACATIONS_DECISION_CIVILIANS_MANY_VACATIONS.JRXML"),

    VACATIONS_EMPLOYEE_VACATIONS("/Reports/Vacations/VACATIONS_EMPLOYEE_VACATIONS.JRXML"),
    VACATIONS_TRANSACTIONS_AND_REQUESTS("/Reports/Vacations/VACATIONS_TRANSACTIONS_AND_REQUESTS.JRXML"),
    VACATIONS_TRANSACTIONS_STATISTICAL("/Reports/Vacations/VACATIONS_TRANSACTIONS_STATISTICAL.JRXML"),
    VACATIONS_TRANSACTIONS_AND_REQUESTS_STATISTICAL("/Reports/Vacations/VACATIONS_TRANSACTIONS_AND_REQUESTS_STATISTICAL.JRXML"),

    VACATIONS_WITHOUT_JOINING_DATE("/Reports/Vacations/VACATIONS_WITHOUT_JOINING_DATE.JRXML"),
    VACATIONS_JOINING_DATE_EXCEEDERS("/Reports/Vacations/VACATIONS_JOINING_DATE_EXCEEDERS.JRXML"),
    VACATIONS_JOINING_DOCUMENT("/Reports/Vacations/VACATIONS_JOINING_DOCUMENT.JRXML"),

    // TRAINING

    TRAINING_DECISION_PLAN_APPROVAL("/Reports/Trainings/TRAINING_DECISION_PLAN_APPROVAL.JRXML"),
    TRAINING_DECISION_PLAN_DETAILS("/Reports/Trainings/TRAINING_DECISION_PLAN_DETAILS.JRXML"),
    TRAINING_PLAN_FINAL_DRAFT("/Reports/Trainings/TRAINING_PLAN_FINAL_DRAFT.JRXML"),
    TRAINING_PLAN_INITIAL_DRAFT("/Reports/Trainings/TRAINING_PLAN_INITIAL_DRAFT.JRXML"),
    TRAINING_PLAN_NEEDS_INQUIRY_BY_COURSE("/Reports/Trainings/TRAINING_PLAN_NEEDS_BY_COURSE.JRXML"),
    TRAINING_PLAN_NEEDS_INQUIRY_BY_REQUESTING_UNIT("/Reports/Trainings/TRAINING_PLAN_NEEDS_BY_REQUESTING_UNIT.JRXML"),
    TRAINING_PLAN_INITIAL_DRAFT_STATISTICS("/Reports/Trainings/TRAINING_PLAN_INITIAL_DRAFT_STATISTICS.JRXML"),
    TRAINING_PLAN_FINAL_DRAFT_STATISTICS("/Reports/Trainings/TRAINING_PLAN_FINAL_DRAFT_STATISTICS.JRXML"),
    TRAINING_PLAN_CANDIDATE_EMPLOYEES("/Reports/Trainings/TRAINING_PLAN_CANDIDATE_EMPLOYEES.JRXML"),

    TRAINING_COURSE_DATA_PLAN_BASED("/Reports/Trainings/TRAINING_COURSE_DATA_PLAN_BASED.JRXML"),
    TRAINING_COURSE_JOINING("/Reports/Trainings/TRAINING_COURSE_JOINING.JRXML"),
    TRAINING_COURSE_RESULTS("/Reports/Trainings/TRAINING_COURSE_RESULTS.JRXML"),
    TRAINING_DECISION_COURSE_START("/Reports/Trainings/TRAINING_DECISION_COURSE_START.JRXML"),
    TRAINING_DECISION_COURSE_MODIFICATION("/Reports/Trainings/TRAINING_DECISION_COURSE_MODIFICATION.JRXML"),
    TRAINING_DECISION_COURSE_POSTPONEMENT("/Reports/Trainings/TRAINING_DECISION_COURSE_POSTPONEMENT.JRXML"),
    TRAINING_DECISION_COURSE_CANCELLATION("/Reports/Trainings/TRAINING_DECISION_COURSE_CANCELLATION.JRXML"),
    TRAINING_CANCELED_TRAINEES_COURSES("/Reports/Trainings/TRAINING_CANCELED_TRAINEES_COURSES.JRXML"),
    TRAINING_DECISION_TRAINEE_ELECTRONIC_CERTIFICATE("/Reports/Trainings/TRAINING_DECISION_TRAINEE_ELECTERONIC_CERTIFICATE.JRXML"),
    TRAINING_DECISION_TRAINEE_CERTIFICATE("/Reports/Trainings/TRAINING_DECISION_TRAINEE_CERTIFICATE.JRXML"),
    TRAINING_DECISION_TRAINEE_COURSE_CANCELLATION("/Reports/Trainings/TRAINING_DECISION_TRAINEE_COURSE_CANCELLATION.JRXML"),
    TRAINING_DECISION_SCHOLARSHIP("/Reports/Trainings/TRAINING_DECISION_SCHOLARSHIP.JRXML"),
    TRAINING_DECISION_SCHOLARSHIP_EXTENSION("/Reports/Trainings/TRAINING_DECISION_SCHOLARSHIP_EXTENSION.JRXML"),
    TRAINING_DECISION_SCHOLARSHIP_TERMINATION("/Reports/Trainings/TRAINING_DECISION_SCHOLARSHIP_TERMINATION.JRXML"),
    TRAINING_DECISION_SCHOLARSHIP_CANCELLATION("/Reports/Trainings/TRAINING_DECISION_SCHOLARSHIP_CANCELLATION.JRXML"),
    TRAINING_DECISION_COURSE_SYLLABUS_APPROVAL("/Reports/Trainings/TRAINING_DECISION_COURSE_SYLLABUS_APPROVAL.JRXML"),
    TRAINING_DECISION_COURSE_SYLLABUS_CANCELLATION("/Reports/Trainings/TRAINING_DECISION_COURSE_SYLLABUS_CANCELLATION.JRXML"),
    TRAINING_EMPLOYEES_TRANSACTIONS("/Reports/Trainings/TRAINING_EMPLOYEES_TRANSACTIONS.JRXML"),
    TRAINING_EMPLOYEES_REQUESTS("/Reports/Trainings/TRAINING_EMPLOYEES_REQUESTS.JRXML"),
    TRAINING_COURSE_JOINING_APPROVAL_DOCUMENT("/Reports/Trainings/TRAINING_COURSE_JOINING_APPROVAL_DOCUMENT.JRXML"),
    TRAINING_COURSE_EVENT_CANDIDATE_EMPLOYEES_STATISTICS("/Reports/Trainings/TRAINING_COURSE_EVENT_CANDIDATE_EMPLOYEES_STATISTICS.JRXML"),

    // RAISES
    ANNUAL_RAISE_DESERVED_EMPLOYEES("/Reports/Raises/ANNUAL_RAISE_DESERVED_EMPLOYEES.JRXML"),
    ADDITIONAL_RAISE_DESERVED_EMPLOYEES("/Reports/Raises/ADDITIONAL_RAISE_DESERVED_EMPLOYEES.JRXML"),
    ANNUAL_RAISE_EXCLUDED_FOR_END_LADDER_EMPLOYEES("/Reports/Raises/ANNUAL_RAISE_EXCLUDED_FOR_END_OF_LADDER.JRXML"),
    ANNUAL_RAISE_EXCLUDED_FOR_ANOTHER_REASON_EMPLOYEES("/Reports/Raises/ANNUAL_RAISE_EXCLUDED_FOR_ANOTHER_REASON.JRXML"),
    ANNUAL_RAISE_NOT_DESERVED_EMPLOYEES("/Reports/Raises/ANNUAL_RAISE_NOT_DESERVED_EMPLOYEES.JRXML"),
    ANNUAL_RAISE_ALL_EXCLUDED_EMPLOYEES("/Reports/Raises/ANNUAL_RAISE_ALL_EXCLUDED_EMPLOYEES.JRXML"),

    // EXERCISES

    EXERCISES_DATA("/Reports/Exercises/EXERCISES_DATA.JRXML"),
    EXERCISES_EMPLOYEES("/Reports/Exercises/EXERCISES_EMPLOYEES.JRXML"),

    // NAVY_FORMATION

    NAVY_FORMATION_REPORT("/Reports/NavyFormation/NAVY_FORMATION_REPORT.JRXML"),

    // MARTYRS REPORTS

    MARTYR_FILE("/Reports/Martyrs/MARTYR_FILE.JRXML"),
    MARTYRS_DATA("/Reports/Martyrs/MARTYRS_DATA.JRXML"),

    // RETIREMENT

    RETIREMENTS_SICK_VACATIONS("/Reports/Retirements/RETIREMENTS_SICK_VACATIONS.JRXML"),
    RETIREMENTS_REGULAR_VACATIONS("/Reports/Retirements/RETIREMENTS_REGULAR_VACATIONS.JRXML"),
    RETIREMENTS_OFFICERS_SERVICES_SUMMARY("/Reports/Retirements/RETIREMENTS_OFFICERS_SERVICES_SUMMARY.JRXML"),
    RETIREMENTS_SERVICES_STATEMENT("/Reports/Retirements/RETIREMENTS_SERVICES_STATEMENT.JRXML"),
    RETIREMENTS_DISCLAIMER_DECISION("/Reports/Retirements/RETIREMENTS_DISCLAIMER_DECISION.JRXML"),

    // DEFINITION_LETTERS

    DEFINITION_LETTERS_BASIC_SALARY("/Reports/DefinitionLetters/DEFINITION_LETTERS_BASIC_SALARY.JRXML"),
    DEFINITION_LETTERS_NET_SALARY("/Reports/DefinitionLetters/DEFINITION_LETTERS_NET_SALARY.JRXML"),
    DEFINITION_LETTERS_NET_SALARY_ENGLISH("/Reports/DefinitionLetters/DEFINITION_LETTERS_NET_SALARY_ENGLISH.JRXML"),
    DEFINITION_LETTERS_TOTAL_SALARY("/Reports/DefinitionLetters/DEFINITION_LETTERS_TOTAL_SALARY.JRXML"),
    DEFINITION_LETTERS_MEDICAL_LETTER("/Reports/DefinitionLetters/DEFINITION_LETTERS_MEDICAL_LETTER.JRXML"),
    DEFINITION_LETTERS_MEDICAL_LETTER_RETIRED("/Reports/DefinitionLetters/DEFINITION_LETTERS_MEDICAL_LETTER_RETIRED.JRXML");

    private String code;

    private ReportNamesEnum(String code) {
	this.code = code;
    }

    public String getCode() {
	return code;
    }
}
