
package com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.code.integration.webservicesclients.yaqeenclient.com.elm.yakeen.yakeen4borderguard.GccInfoByNINResult;
import com.code.integration.webservicesclients.yaqeenclient.com.elm.yakeen.yakeen4borderguard.GccInfoByPassportResult;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebService(name = "YaqeenServices",
	targetNamespace = "http://com.ejada.yaqeen/")
@XmlSeeAlso({
	com.code.integration.webservicesclients.yaqeenclient.com.elm.yakeen.yakeen4borderguard.ObjectFactory.class,
	com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.ObjectFactory.class
})
public interface YaqeenServices {

    /**
     * 
     * @param personInfoRequest
     * @return returns yaqeen.ejada.com.PersonInfoDetailedResult
     * @throws DataValidationException
     * @throws BusinessException_Exception
     * @throws Yakeen4BorderGuardFaultException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonInfoDetailed",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetPersonInfoDetailed")
    @ResponseWrapper(localName = "getPersonInfoDetailedResponse",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetPersonInfoDetailedResponse")
    @Action(input = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoDetailedRequest",
	    output = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoDetailedResponse",
	    fault = {
		    @FaultAction(className = Yakeen4BorderGuardFaultException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoDetailed/Fault/Yakeen4BorderGuardFault_Exception"),
		    @FaultAction(className = DataValidationException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoDetailed/Fault/DataValidationException"),
		    @FaultAction(className = BusinessException_Exception.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoDetailed/Fault/BusinessException")
	    })
    public PersonInfoDetailedResult getPersonInfoDetailed(
	    @WebParam(name = "PersonInfoRequest",
		    targetNamespace = "") PersonInfoRequest personInfoRequest)
	    throws BusinessException_Exception, DataValidationException, Yakeen4BorderGuardFaultException;

    /**
     * 
     * @param gccInfoByNINRequest
     * @return returns com.elm.yakeen.yakeen4borderguard.GccInfoByNINResult
     * @throws DataValidationException
     * @throws BusinessException_Exception
     * @throws Yakeen4BorderGuardFaultException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGCCInfoByNIN",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetGCCInfoByNIN")
    @ResponseWrapper(localName = "getGCCInfoByNINResponse",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetGCCInfoByNINResponse")
    @Action(input = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByNINRequest",
	    output = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByNINResponse",
	    fault = {
		    @FaultAction(className = Yakeen4BorderGuardFaultException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByNIN/Fault/Yakeen4BorderGuardFault_Exception"),
		    @FaultAction(className = DataValidationException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByNIN/Fault/DataValidationException"),
		    @FaultAction(className = BusinessException_Exception.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByNIN/Fault/BusinessException")
	    })
    public GccInfoByNINResult getGCCInfoByNIN(
	    @WebParam(name = "GccInfoByNINRequest",
		    targetNamespace = "") YaqeenGccInfoByNINRequest gccInfoByNINRequest)
	    throws BusinessException_Exception, DataValidationException, Yakeen4BorderGuardFaultException;

    /**
     * 
     * @param personInfoRequest
     * @return returns yaqeen.ejada.com.PerosnInfoResult
     * @throws DataValidationException
     * @throws BusinessException_Exception
     * @throws Yakeen4BorderGuardFaultException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonInfo",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetPersonInfo")
    @ResponseWrapper(localName = "getPersonInfoResponse",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetPersonInfoResponse")
    @Action(input = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoRequest",
	    output = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoResponse",
	    fault = {
		    @FaultAction(className = Yakeen4BorderGuardFaultException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfo/Fault/Yakeen4BorderGuardFault_Exception"),
		    @FaultAction(className = DataValidationException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfo/Fault/DataValidationException"),
		    @FaultAction(className = BusinessException_Exception.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfo/Fault/BusinessException")
	    })
    public PerosnInfoResult getPersonInfo(
	    @WebParam(name = "PersonInfoRequest",
		    targetNamespace = "") PersonInfoRequest personInfoRequest)
	    throws BusinessException_Exception, DataValidationException, Yakeen4BorderGuardFaultException;

    /**
     * 
     * @param gccInfoByPassportRequest
     * @return returns com.elm.yakeen.yakeen4borderguard.GccInfoByPassportResult
     * @throws DataValidationException
     * @throws BusinessException_Exception
     * @throws Yakeen4BorderGuardFaultException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGCCInfoByPassport",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetGCCInfoByPassport")
    @ResponseWrapper(localName = "getGCCInfoByPassportResponse",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetGCCInfoByPassportResponse")
    @Action(input = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByPassportRequest",
	    output = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByPassportResponse",
	    fault = {
		    @FaultAction(className = Yakeen4BorderGuardFaultException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByPassport/Fault/Yakeen4BorderGuardFault_Exception"),
		    @FaultAction(className = DataValidationException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByPassport/Fault/DataValidationException"),
		    @FaultAction(className = BusinessException_Exception.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getGCCInfoByPassport/Fault/BusinessException")
	    })
    public GccInfoByPassportResult getGCCInfoByPassport(
	    @WebParam(name = "GccInfoByPassportRequest",
		    targetNamespace = "") YaqeenGccInfoByPassportRequest gccInfoByPassportRequest)
	    throws BusinessException_Exception, DataValidationException, Yakeen4BorderGuardFaultException;

    /**
     * 
     * @param carInfoByPlateRequest
     * @return returns yaqeen.ejada.com.CarInfoResult
     * @throws DataValidationException
     * @throws BusinessException_Exception
     * @throws Yakeen4BorderGuardFaultException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarInfoByPlate",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetCarInfoByPlate")
    @ResponseWrapper(localName = "getCarInfoByPlateResponse",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetCarInfoByPlateResponse")
    @Action(input = "http://com.ejada.yaqeen/YaqeenServices/getCarInfoByPlateRequest",
	    output = "http://com.ejada.yaqeen/YaqeenServices/getCarInfoByPlateResponse",
	    fault = {
		    @FaultAction(className = Yakeen4BorderGuardFaultException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getCarInfoByPlate/Fault/Yakeen4BorderGuardFault_Exception"),
		    @FaultAction(className = DataValidationException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getCarInfoByPlate/Fault/DataValidationException"),
		    @FaultAction(className = BusinessException_Exception.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getCarInfoByPlate/Fault/BusinessException")
	    })
    public CarInfoResult getCarInfoByPlate(
	    @WebParam(name = "CarInfoByPlateRequest",
		    targetNamespace = "") YaqeenCarInfoByPlateRequest carInfoByPlateRequest)
	    throws BusinessException_Exception, DataValidationException, Yakeen4BorderGuardFaultException;

    /**
     * 
     * @param personInfoRequest
     * @return returns yaqeen.ejada.com.PersonInfoResultWithSecurityStatus
     * @throws DataValidationException
     * @throws BusinessException_Exception
     * @throws Yakeen4BorderGuardFaultException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonInfoWithSecuirtyStatus",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetPersonInfoWithSecuirtyStatus")
    @ResponseWrapper(localName = "getPersonInfoWithSecuirtyStatusResponse",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetPersonInfoWithSecuirtyStatusResponse")
    @Action(input = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithSecuirtyStatusRequest",
	    output = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithSecuirtyStatusResponse",
	    fault = {
		    @FaultAction(className = Yakeen4BorderGuardFaultException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithSecuirtyStatus/Fault/Yakeen4BorderGuardFault_Exception"),
		    @FaultAction(className = DataValidationException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithSecuirtyStatus/Fault/DataValidationException"),
		    @FaultAction(className = BusinessException_Exception.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithSecuirtyStatus/Fault/BusinessException")
	    })
    public PersonInfoResultWithSecurityStatus getPersonInfoWithSecuirtyStatus(
	    @WebParam(name = "PersonInfoRequest",
		    targetNamespace = "") PersonInfoRequest personInfoRequest)
	    throws BusinessException_Exception, DataValidationException, Yakeen4BorderGuardFaultException;

    /**
     * 
     * @param personInfoRequest
     * @return returns yaqeen.ejada.com.PersonInfoResultWithDetailedSecurityStatus
     * @throws DataValidationException
     * @throws BusinessException_Exception
     * @throws Yakeen4BorderGuardFaultException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonInfoWithDetailedSecuirtyStatus",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetPersonInfoWithDetailedSecuirtyStatus")
    @ResponseWrapper(localName = "getPersonInfoWithDetailedSecuirtyStatusResponse",
	    targetNamespace = "http://com.ejada.yaqeen/",
	    className = "com.code.integration.webservicesclients.yaqeenclient.yaqeen.ejada.com.GetPersonInfoWithDetailedSecuirtyStatusResponse")
    @Action(input = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithDetailedSecuirtyStatusRequest",
	    output = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithDetailedSecuirtyStatusResponse",
	    fault = {
		    @FaultAction(className = Yakeen4BorderGuardFaultException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithDetailedSecuirtyStatus/Fault/Yakeen4BorderGuardFault_Exception"),
		    @FaultAction(className = DataValidationException.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithDetailedSecuirtyStatus/Fault/DataValidationException"),
		    @FaultAction(className = BusinessException_Exception.class,
			    value = "http://com.ejada.yaqeen/YaqeenServices/getPersonInfoWithDetailedSecuirtyStatus/Fault/BusinessException")
	    })
    public PersonInfoResultWithDetailedSecurityStatus getPersonInfoWithDetailedSecuirtyStatus(
	    @WebParam(name = "PersonInfoRequest",
		    targetNamespace = "") PersonInfoRequest personInfoRequest)
	    throws BusinessException_Exception, DataValidationException, Yakeen4BorderGuardFaultException;

}
